# Generated by Django 5.1.5 on 2025-08-09 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(blank=True, choices=[('btech', 'B.Tech'), ('be', 'B.E.'), ('btech_cse', 'B.Tech Computer Science'), ('btech_ece', 'B.Tech Electronics & Communication'), ('btech_eee', 'B.Tech Electrical & Electronics'), ('btech_mech', 'B.Tech Mechanical'), ('btech_civil', 'B.Tech Civil'), ('btech_chemical', 'B.Tech Chemical'), ('btech_it', 'B.Tech Information Technology'), ('bsc', 'B.Sc.'), ('bsc_physics', 'B.Sc. Physics'), ('bsc_chemistry', 'B.Sc. Chemistry'), ('bsc_mathematics', 'B.Sc. Mathematics'), ('bsc_biology', 'B.Sc. Biology'), ('bsc_botany', 'B.Sc. Botany'), ('bsc_zoology', 'B.Sc. Zoology'), ('bsc_microbiology', 'B.Sc. Microbiology'), ('bsc_biotechnology', 'B.Sc. Biotechnology'), ('bsc_cs', 'B.Sc. Computer Science'), ('bsc_it', 'B.Sc. Information Technology'), ('bsc_statistics', 'B.Sc. Statistics'), ('bsc_geology', 'B.Sc. Geology'), ('bsc_geography', 'B.Sc. Geography'), ('bcom', 'B.Com'), ('bcom_honours', 'B.Com (Honours)'), ('bba', 'BBA'), ('ba', 'B.A.'), ('ba_english', 'B.A. English'), ('ba_hindi', 'B.A. Hindi'), ('ba_history', 'B.A. History'), ('ba_political_science', 'B.A. Political Science'), ('ba_economics', 'B.A. Economics'), ('ba_sociology', 'B.A. Sociology'), ('ba_psychology', 'B.A. Psychology'), ('ba_philosophy', 'B.A. Philosophy'), ('ba_journalism', 'B.A. Journalism'), ('bca', 'BCA'), ('bcs', 'BCS'), ('llb', 'LLB'), ('bjmc', 'BJMC'), ('bfa', 'BFA'), ('bed', 'B.Ed'), ('bpharm', 'B.Pharm'), ('bds', 'BDS'), ('bhms', 'BHMS'), ('bams', 'BAMS'), ('bnys', 'BNYS'), ('bpt', 'BPT'), ('bvsc', 'BVSc'), ('barch', 'B.Arch'), ('bdes', 'B.Des'), ('bhtm', 'BHTM'), ('bmm', 'BMM'), ('mbbs', 'MBBS'), ('mtech', 'M.Tech'), ('me', 'M.E.'), ('ms', 'M.S.'), ('mba', 'MBA'), ('mba_finance', 'MBA Finance'), ('mba_marketing', 'MBA Marketing'), ('mba_hr', 'MBA HR'), ('mba_operations', 'MBA Operations'), ('mba_it', 'MBA IT'), ('pgdm', 'PGDM'), ('msc', 'M.Sc.'), ('msc_physics', 'M.Sc. Physics'), ('msc_chemistry', 'M.Sc. Chemistry'), ('msc_mathematics', 'M.Sc. Mathematics'), ('msc_biology', 'M.Sc. Biology'), ('msc_cs', 'M.Sc. Computer Science'), ('msc_it', 'M.Sc. Information Technology'), ('msc_biotechnology', 'M.Sc. Biotechnology'), ('msc_statistics', 'M.Sc. Statistics'), ('mcom', 'M.Com'), ('ma', 'M.A.'), ('ma_english', 'M.A. English'), ('ma_hindi', 'M.A. Hindi'), ('ma_history', 'M.A. History'), ('ma_political_science', 'M.A. Political Science'), ('ma_economics', 'M.A. Economics'), ('ma_sociology', 'M.A. Sociology'), ('ma_psychology', 'M.A. Psychology'), ('mca', 'MCA'), ('llm', 'LLM'), ('med', 'M.Ed'), ('mpharm', 'M.Pharm'), ('mds', 'MDS'), ('march', 'M.Arch'), ('mdes', 'M.Des'), ('mjmc', 'MJMC'), ('mfa', 'MFA'), ('mpt', 'MPT'), ('mvsc', 'MVSc'), ('md', 'MD'), ('ms_medical', 'MS (Medical)'), ('dm', 'DM'), ('mch', 'MCh'), ('phd', 'Ph.D'), ('diploma', 'Diploma'), ('polytechnic', 'Polytechnic'), ('iti', 'ITI'), ('12th', '12th Pass'), ('graduation', 'Graduate'), ('postgraduation', 'Post Graduate'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in meters (e.g., 1.75)', null=True, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='open_to_pets',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='open_to_relocate',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='undergraduate_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='want_kids',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=10, null=True),
        ),
    ]
