# Generated by Django 5.1.5 on 2025-08-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailwhitelist_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailwhitelist',
            old_name='email',
            new_name='username',
        ),
    ]
