# Generated by Django 5.1.5 on 2025-08-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_email_emailwhitelist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailwhitelist',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
